import { TaskProvider } from '../context/TaskContext'
import Layout from '@/components/Layout'
import { Toaster } from './Toaster'
import './globals.css'

import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        <TaskProvider>
          {/* <h1>Navigation</h1> */}

          <Navbar />

          <Layout>
            {children}
          </Layout>

          <Toaster />
        </TaskProvider>
      </body>
    </html>
  )
}
