import { TaskProvider } from '../context/TaskContext'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <TaskProvider>
        <body>
          <h1>Navigation</h1>
          {children}
        </body>
      </TaskProvider>
    </html>
  )
}
